sonar.projectKey=dev_cloudgateway
sonar.projectName=dev_cloudgateway
sonar.host.url=https://devyreham.com/sq

# defaults to 'not provided'
# sonar.projectVersion=4.4

# Encoding of the source code. Default is default system encoding
sonar.qualitygate.wait=true
sonar.sources=src/main/java
sonar.tests=src/test/java

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.libraries=**/*.jar
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test